### PR TITLE
Byte order + Block size restriction

### LINKED ISSUE #8: Use specific endianness for block headers
We should use a specific byte ordering instead of the machine byte ordering otherwise the code will not work across machines with different byte ordering. We can raise an issue for this and address it separately.

### LINKED ISSUE #41: Restrict block size when compressing.
Check the size of the input array and fail if it is more than the max block size set in BlockConfig. Otherwise decompression would fail.

### PR DESCRIPTION
**Pull request by adithyaov**

### CODE REVIEW

File: src/Streamly/Internal/LZ4.hs [hunk 1]
```diff
@@ -73,6 +73,28 @@ import Streamly.Internal.LZ4.Config
...
 
+--------------------------------------------------------------------------------
+-- Endianess
+--------------------------------------------------------------------------------
+
+{-# NOINLINE isLittleEndianMachine #-}
+isLittleEndianMachine :: Bool
+isLittleEndianMachine = unsafePerformIO $ do
+    let arr = Array.fromList [1 :: Word32]
+    Array.unsafeAsPtr arr
```
Comment (harendra-kumar) [inline src/Streamly/Internal/LZ4.hs]: You can use `Array.asBytes` instead.

File: src/Streamly/Internal/LZ4.hs [hunk 2]
```diff
@@ -73,6 +73,28 @@ import Streamly.Internal.LZ4.Config
...
+        $ \src -> do
+              b0 <- peek (castPtr src :: Ptr Word8)
+              return $ b0 == 0
```
Comment (harendra-kumar) [inline src/Streamly/Internal/LZ4.hs]: isn't this big endian?

File: src/Streamly/Internal/LZ4.hs [hunk 3]
```diff
@@ -73,6 +73,28 @@ import Streamly.Internal.LZ4.Config
...
+
+{-# INLINE toLittleEndian #-}
+toLittleEndian :: Int32 -> Int32
+toLittleEndian i32
+    | isLittleEndianMachine = i32
+    | otherwise = fromIntegral (byteSwap32 (fromIntegral i32))
```
Comment (harendra-kumar) [inline src/Streamly/Internal/LZ4.hs:90]: Ah, should have been named `byteReverse32` instead.

File: src/Streamly/Internal/LZ4.hs [hunk 4]
```diff
@@ -213,8 +237,14 @@ compressChunk cfg speed ctx arr = do
...
                   speedC = unsafeIntToCInt speed
+                  maxBlockSize = blockSizeToInt $ blockSize cfg
               -- Ideally the maxCLen check below covers this case, but just in
               -- case.
+              when (uncompLen > maxBlockSize)
+                $ error $ "compressChunk: Source array length "
+                    ++ show uncompLen
+                    ++ " exceeds the max block size in the config "
+                    ++ show maxBlockSize
               when (uncompLen > maxUncompLen)
```
Comment (harendra-kumar) [inline src/Streamly/Internal/LZ4.hs]: We can restrict the maxBlockSize to maxUncompLen, so this check would be covered in the previous check itself.

File: src/Streamly/Internal/LZ4/Config.hs [hunk 5]
```diff
@@ -115,6 +116,13 @@ data BlockSize =
     | BlockMax1MB
     | BlockMax4MB
 
+blockSizeToInt :: BlockSize -> Int
+blockSizeToInt BlockHasSize = maxBound
```
Comment (harendra-kumar) [inline src/Streamly/Internal/LZ4/Config.hs]: We can restrict this to maxUncompLen.

Comment (harendra-kumar) [reply src/Streamly/Internal/LZ4/Config.hs]: Move this function to LZ4.hs  where it is actually used.

**Review by harendra-kumar — CHANGES_REQUESTED** [review]

File: src/Streamly/Internal/LZ4.hs (hunk 2 above)
Comment (adithyaov) [reply src/Streamly/Internal/LZ4.hs]: Ah! You're right. Either way, it does not matter. The function needs to be renamed.

File: src/Streamly/Internal/LZ4/Config.hs (hunk 5 above)
Comment (adithyaov) [reply src/Streamly/Internal/LZ4/Config.hs]: This behaves like an instance almost? Only one right answer for this. Having this locally with the type makes more sense to me.

Comment (adithyaov) [reply src/Streamly/Internal/LZ4/Config.hs]: I'll move it anyway. (Dependency issue)

File: src/Streamly/Internal/LZ4.hs (hunk 2 above)
Comment (harendra-kumar) [reply src/Streamly/Internal/LZ4.hs]: It should matter, we will end up using big-endian numbers in the header instead of little-endian.

File: src/Streamly/Internal/LZ4/Config.hs (hunk 5 above)
Comment (harendra-kumar) [reply src/Streamly/Internal/LZ4/Config.hs]: If this function is used by multiple modules then it makes sense to keep it in a common module. Otherwise I like to keep a function close to where it is used. Closely related code goes together.
